name: simple tests

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Make
      run: make simple
    - name: Run
      run: ./bdd_simple
       
  build-macos:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Make
      run: make simple
    - name: Run
      run: ./bdd_simple
         
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Make
      run: make simple
    - name: Run
      run: .\bdd_simple
